# Generated by Django 5.2.15 on 2026-07-24 05:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def normalize_project_governance(apps, schema_editor):
    Project = apps.get_model("projects", "ResearchProject")
    Membership = apps.get_model("projects", "ProjectMembership")
    now = timezone.now()
    for project in Project.objects.select_related("advisor").iterator():
        owner = project.advisor
        eligible = (
            owner.global_role == "advisor"
            and owner.status == "active"
            and owner.active_role == "teacher"
            and owner.email_verified_at is not None
        )
        Membership.objects.filter(
            project=project,
            role="advisor",
            status="active",
        ).exclude(user=owner).update(
            role="co_advisor",
            role_changed_at=now,
        )
        if eligible:
            Membership.objects.update_or_create(
                project=project,
                user=owner,
                defaults={
                    "role": "advisor",
                    "status": "active",
                    "removed_at": None,
                    "role_changed_at": now,
                },
            )
            continue
        project.governance_state = "hold"
        project.governance_hold_reason = (
            "legacy_admin_owner" if owner.global_role == "admin" else "owner_ineligible"
        )
        project.governance_hold_started_at = now
        project.save(
            update_fields=[
                "governance_state",
                "governance_hold_reason",
                "governance_hold_started_at",
            ]
        )
        Membership.objects.filter(
            project=project,
            user=owner,
            role="advisor",
            status="active",
        ).update(status="removed", removed_at=now)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_materials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectOwnershipTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "previous_advisor_result",
                    models.CharField(
                        choices=[
                            ("co_advisor", "Co-advisor"),
                            ("reviewer", "Reviewer"),
                            ("observer", "Observer"),
                            ("removed", "Removed"),
                        ],
                        default="co_advisor",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("expected_project_version", models.PositiveIntegerField()),
                ("idempotency_key", models.CharField(blank=True, max_length=100)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_project_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="assignment_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="role_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="governance_hold_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner_ineligible", "Owner ineligible"),
                    ("legacy_admin_owner", "Legacy administrator owner"),
                    ("migration_conflict", "Migration conflict"),
                    ("manual_correction", "Manual correction"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="governance_hold_resolution_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="governance_hold_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="governance_hold_resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_project_governance_holds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="governance_hold_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="governance_state",
            field=models.CharField(
                choices=[("normal", "Normal"), ("hold", "Hold")], default="normal", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="governance_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("advisor", "Advisor"),
                    ("co_advisor", "Co-advisor"),
                    ("student", "Student"),
                    ("reviewer", "Reviewer"),
                    ("observer", "Observer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project", "role", "status"], name="project_member_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["user", "role", "status"], name="project_member_user_idx"),
        ),
        migrations.RunPython(normalize_project_governance, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "advisor"), ("status", "active")),
                fields=("project",),
                name="unique_active_primary_advisor",
            ),
        ),
        migrations.AddField(
            model_name="projectownershiptransfer",
            name="initiated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiated_project_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectownershiptransfer",
            name="new_advisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_project_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectownershiptransfer",
            name="previous_advisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_project_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectownershiptransfer",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ownership_transfers",
                to="projects.researchproject",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectownershiptransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("previous_advisor", models.F("new_advisor")), _negated=True),
                name="project_transfer_advisors_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectownershiptransfer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("project", "idempotency_key"),
                name="unique_project_transfer_idempotency",
            ),
        ),
    ]
