# Generated by Django 5.2.15 for feature 017 research execution.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_access_governance_roles"),
        ("submissions", "0007_review_assignments"),
        ("tasks", "0002_task_assignees"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=8000)),
                ("acceptance_criteria", models.TextField(max_length=8000)),
                ("due_date", models.DateField()),
                ("required", models.BooleanField(default=True)),
                ("reviewer_required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField()),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("blocked", "Blocked"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("changes_requested", "Changes requested"),
                            ("accepted", "Accepted"),
                            ("archived", "Archived"),
                        ],
                        default="planned",
                        max_length=24,
                    ),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("blocker_summary", models.TextField(blank=True, max_length=2000)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_deliverables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="projects.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["milestone_id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DeliverableRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("criteria_snapshot", models.TextField(max_length=8000)),
                ("description_snapshot", models.TextField(max_length=8000)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("recommended_accept", "Recommended accept"),
                            ("recommended_return", "Recommended return"),
                            ("accepted", "Accepted"),
                            ("returned", "Returned"),
                        ],
                        default="submitted",
                        max_length=24,
                    ),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="projects.deliverable",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_revisions",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_deliverable_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-revision_number"],
            },
        ),
        migrations.CreateModel(
            name="DeliverableReviewRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[("accept", "Accept"), ("return", "Return")], max_length=10
                    ),
                ),
                ("rationale", models.TextField(max_length=8000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_recommendations",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "review_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliverable_recommendations",
                        to="submissions.submissionreviewassignment",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliverable_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="projects.deliverablerevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverableFinalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("returned", "Returned")], max_length=10
                    ),
                ),
                ("rationale", models.TextField(blank=True, max_length=8000)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=100)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliverable_final_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_decisions",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_decision",
                        to="projects.deliverablerevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverableEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_url", models.URLField(blank=True, max_length=2048)),
                ("label_snapshot", models.CharField(max_length=255)),
                (
                    "source_type_snapshot",
                    models.CharField(
                        choices=[
                            ("project_material", "Project material"),
                            ("task", "Task"),
                            ("weekly_progress_report", "Weekly progress report"),
                            ("external_url", "External URL"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_id_snapshot", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="added_deliverable_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_evidence",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "project_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliverable_evidence",
                        to="projects.projectmaterial",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliverable_evidence",
                        to="tasks.task",
                    ),
                ),
                (
                    "weekly_progress_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliverable_evidence",
                        to="submissions.weeklyprogressreport",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="projects.deliverablerevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deliverable",
            name="accepted_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="projects.deliverablerevision",
            ),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="projects.deliverablerevision",
            ),
        ),
        migrations.CreateModel(
            name="DeliverableTaskLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_links",
                        to="projects.deliverable",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_deliverable_task_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_links",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=8000)),
                ("target_date", models.DateField()),
                ("order", models.PositiveIntegerField()),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("at_risk", "At risk"),
                            ("blocked", "Blocked"),
                            ("overdue", "Overdue"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="deliverable",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliverables",
                to="projects.milestone",
            ),
        ),
        migrations.CreateModel(
            name="MilestoneOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_milestone_owners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="projects.milestone",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverableAssignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_deliverable_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignees",
                        to="projects.deliverable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliverable_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "removed_at", "deliverable"],
                        name="deliverable_assignee_user_idx",
                    ),
                    models.Index(
                        fields=["deliverable", "removed_at"], name="deliverable_assignee_open_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=("deliverable", "user"),
                        name="unique_open_deliverable_assignee",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliverableReviewerDesignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("designated_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_designations",
                        to="projects.deliverable",
                    ),
                ),
                (
                    "designated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_deliverable_reviewer_designations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="designated_deliverable_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["deliverable", "removed_at"], name="deliverable_reviewer_open_idx"
                    ),
                    models.Index(
                        fields=["reviewer", "removed_at", "deliverable"],
                        name="deliverable_reviewer_user_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=("deliverable", "reviewer"),
                        name="unique_open_deliverable_reviewer",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="deliverablerevision",
            index=models.Index(
                fields=["deliverable", "-revision_number"], name="deliverable_revision_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverablerevision",
            index=models.Index(
                fields=["project", "state", "submitted_at"], name="deliverable_revision_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverablerevision",
            constraint=models.UniqueConstraint(
                fields=("deliverable", "revision_number"), name="unique_deliverable_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverablerevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("deliverable", "idempotency_key"),
                name="unique_deliverable_revision_retry",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverablereviewrecommendation",
            index=models.Index(
                fields=["revision", "superseded_at", "created_at"], name="deliver_recommend_rev_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverablereviewrecommendation",
            index=models.Index(
                fields=["reviewer", "superseded_at", "created_at"],
                name="deliver_recommend_user_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverablereviewrecommendation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("superseded_at__isnull", True)),
                fields=("revision", "reviewer"),
                name="unique_open_deliverable_recommendation",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverablefinaldecision",
            index=models.Index(
                fields=["project", "decision", "decided_at"], name="deliver_decision_project_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverablefinaldecision",
            index=models.Index(fields=["revision", "decided_at"], name="deliver_decision_rev_idx"),
        ),
        migrations.AddConstraint(
            model_name="deliverablefinaldecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("project", "idempotency_key"),
                name="unique_deliverable_decision_retry",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverableevidence",
            index=models.Index(fields=["revision", "id"], name="deliverable_evidence_rev_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverableevidence",
            index=models.Index(
                fields=["project_material", "revision"], name="deliverable_evidence_mat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverableevidence",
            index=models.Index(fields=["task", "revision"], name="deliverable_evidence_task_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverableevidence",
            index=models.Index(
                fields=["weekly_progress_report", "revision"], name="deliver_evidence_report_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverabletasklink",
            index=models.Index(fields=["task", "deliverable"], name="deliverable_task_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverabletasklink",
            index=models.Index(fields=["deliverable", "task"], name="deliverable_link_idx"),
        ),
        migrations.AddConstraint(
            model_name="deliverabletasklink",
            constraint=models.UniqueConstraint(
                fields=("deliverable", "task"), name="unique_deliverable_task_link"
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["project", "current_status", "target_date", "order"],
                name="project_milestone_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["project", "archived_at", "order"], name="project_milestone_archive_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.UniqueConstraint(
                fields=("project", "order"), name="unique_project_milestone_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", False), ("current_status", "completed")),
                    models.Q(
                        models.Q(("current_status", "completed"), _negated=True),
                        ("completed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="milestone_completed_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archived_at__isnull", False), ("current_status", "archived")),
                    models.Q(
                        models.Q(("current_status", "archived"), _negated=True),
                        ("archived_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="milestone_archived_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["project", "current_status", "due_date"],
                name="deliverable_project_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["milestone", "required", "current_status"],
                name="deliverable_required_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["project", "archived_at", "updated_at"], name="deliverable_archive_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverable",
            constraint=models.UniqueConstraint(
                fields=("milestone", "order"), name="unique_milestone_deliverable_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverable",
            constraint=models.CheckConstraint(
                condition=models.Q(("progress_percent__gte", 0), ("progress_percent__lte", 100)),
                name="deliverable_progress_range",
            ),
        ),
        migrations.AddIndex(
            model_name="milestoneowner",
            index=models.Index(fields=["user", "milestone"], name="milestone_owner_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="milestoneowner",
            constraint=models.UniqueConstraint(
                fields=("milestone", "user"), name="unique_milestone_owner"
            ),
        ),
    ]
