# Generated by Django 5.2.15 on 2026-07-28 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_research_execution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("context", models.TextField(max_length=8000)),
                ("options_considered", models.JSONField(default=list)),
                ("outcome", models.TextField(max_length=8000)),
                ("rationale", models.TextField(max_length=8000)),
                ("effective_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("current", "Current"), ("superseded", "Superseded")],
                        default="current",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_project_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_project_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="projects.decisionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RiskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=8000)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("report_blocker", "Report blocker"),
                            ("deliverable", "Deliverable"),
                            ("decision", "Decision"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("source_key", models.CharField(blank=True, max_length=160)),
                (
                    "likelihood",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("treatment", models.TextField(blank=True, max_length=8000)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("raised", "Raised"),
                            ("open", "Open"),
                            ("mitigating", "Mitigating"),
                            ("accepted", "Accepted"),
                            ("resolved", "Resolved"),
                        ],
                        default="raised",
                        max_length=16,
                    ),
                ),
                ("closure_rationale", models.TextField(blank=True, max_length=8000)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("idempotency_key", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_project_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raised_project_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["state", "-severity", "review_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectRecordLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_type_snapshot", models.CharField(max_length=40)),
                ("target_id_snapshot", models.CharField(max_length=80)),
                ("label_snapshot", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_project_record_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="projects.decisionrecord",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_links",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="projects.riskrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "previous_state",
                    models.CharField(
                        choices=[
                            ("raised", "Raised"),
                            ("open", "Open"),
                            ("mitigating", "Mitigating"),
                            ("accepted", "Accepted"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("raised", "Raised"),
                            ("open", "Open"),
                            ("mitigating", "Mitigating"),
                            ("accepted", "Accepted"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "likelihood",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        max_length=10,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        max_length=10,
                    ),
                ),
                ("owner_id_snapshot", models.PositiveBigIntegerField(blank=True, null=True)),
                ("treatment", models.TextField(blank=True, max_length=8000)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("closure_rationale", models.TextField(blank=True, max_length=8000)),
                ("reason", models.TextField(max_length=8000)),
                ("idempotency_key", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_risk_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_revisions",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="projects.riskrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-revision_number"],
            },
        ),
        migrations.AddIndex(
            model_name="decisionrecord",
            index=models.Index(
                fields=["project", "status", "effective_date"], name="project_decision_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decisionrecord",
            index=models.Index(
                fields=["project", "owner", "status"], name="project_decision_owner_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="decisionrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("project", "idempotency_key"),
                name="unique_project_decision_retry",
            ),
        ),
        migrations.AddIndex(
            model_name="riskrecord",
            index=models.Index(
                fields=["project", "state", "severity", "review_date"],
                name="project_risk_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskrecord",
            index=models.Index(
                fields=["owner", "state", "review_date"], name="project_risk_owner_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskrecord",
            index=models.Index(
                fields=["project", "source_type", "source_key"], name="project_risk_source_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="riskrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_key", ""), _negated=True),
                fields=("project", "source_type", "source_key"),
                name="unique_project_risk_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("project", "idempotency_key"),
                name="unique_project_risk_retry",
            ),
        ),
        migrations.AddIndex(
            model_name="projectrecordlink",
            index=models.Index(fields=["decision", "id"], name="decision_record_link_idx"),
        ),
        migrations.AddIndex(
            model_name="projectrecordlink",
            index=models.Index(fields=["risk", "id"], name="risk_record_link_idx"),
        ),
        migrations.AddConstraint(
            model_name="projectrecordlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decision__isnull", False), ("risk__isnull", True)),
                    models.Q(("decision__isnull", True), ("risk__isnull", False)),
                    _connector="OR",
                ),
                name="project_record_link_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrecordlink",
            constraint=models.UniqueConstraint(
                fields=("decision", "target_type_snapshot", "target_id_snapshot"),
                name="unique_decision_record_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrecordlink",
            constraint=models.UniqueConstraint(
                fields=("risk", "target_type_snapshot", "target_id_snapshot"),
                name="unique_risk_record_link",
            ),
        ),
        migrations.AddIndex(
            model_name="riskrevision",
            index=models.Index(
                fields=["risk", "-revision_number"], name="project_risk_revision_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="riskrevision",
            constraint=models.UniqueConstraint(
                fields=("risk", "revision_number"), name="unique_project_risk_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="riskrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("risk", "idempotency_key"),
                name="unique_project_risk_transition_retry",
            ),
        ),
    ]
