# Generated by Django 5.2.15 on 2026-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_uploaded_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="category",
            field=models.CharField(
                choices=[
                    ("paper", "Paper"),
                    ("code", "Code archive"),
                    ("document", "Document"),
                    ("writing", "Writing"),
                    ("feedback", "Feedback"),
                    ("audit_export", "Audit export"),
                ],
                max_length=20,
            ),
        ),
    ]
