# Generated by Django 5.2.15 on 2026-07-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_collaboration_notification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="delivery_policy",
            field=models.CharField(
                choices=[("in_app", "In app"), ("in_app_email", "In app and email")],
                default="in_app_email",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("verification_code", "Verification code"),
                    ("role_activation", "Role activation"),
                    ("new_submission", "New submission"),
                    ("pending_review", "Pending review"),
                    ("approaching_deadline", "Approaching deadline"),
                    ("booking_changed", "Booking changed"),
                    ("teacher_feedback", "Teacher feedback"),
                    ("teacher_feedback_available", "Teacher feedback available"),
                    ("membership_changed", "Membership changed"),
                    ("resource_use_decision", "Resource use decision"),
                    ("schedule_published", "Schedule published"),
                    ("schedule_changed", "Schedule changed"),
                    ("schedule_cancelled", "Schedule cancelled"),
                    ("schedule_recipient_removed", "Schedule recipient removed"),
                    ("schedule_reminder", "Schedule reminder"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("retry_needed", "Retry needed"),
                    ("skipped", "Skipped"),
                    ("in_app_only", "In app only"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
