# Generated by Django 5.2.15 on 2026-07-24 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_account_security_event_types"),
        ("projects", "0003_access_governance_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationCategoryPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("project", "Project"),
                            ("deliverable", "Deliverable"),
                            ("report", "Report"),
                            ("decision", "Decision"),
                            ("risk", "Risk"),
                            ("schedule", "Schedule"),
                            ("administration", "Administration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In app"), ("email", "Email")], max_length=20
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("eligible_at", models.DateTimeField()),
                ("attempted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_reason_masked", models.CharField(blank=True, max_length=500)),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["notification_id", "channel", "attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreferenceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("timezone_name", models.CharField(default="UTC", max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectNotificationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reminder_lead_minutes", models.PositiveIntegerField(default=1440)),
                ("escalation_delay_minutes", models.PositiveIntegerField(default=1440)),
                ("repeat_interval_minutes", models.PositiveIntegerField(default=1440)),
                ("max_reminders", models.PositiveSmallIntegerField(default=3)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="action_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="active_follow_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("security", "Security"),
                    ("project", "Project"),
                    ("deliverable", "Deliverable"),
                    ("report", "Report"),
                    ("decision", "Decision"),
                    ("risk", "Risk"),
                    ("schedule", "Schedule"),
                    ("administration", "Administration"),
                ],
                db_index=True,
                default="administration",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="completion_event_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="notification",
            name="completion_event_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="notification",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="notification",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="escalation_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="last_escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="last_reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="outcome_state",
            field=models.CharField(
                choices=[
                    ("not_required", "Not required"),
                    ("pending", "Pending"),
                    ("acknowledged", "Acknowledged"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("unavailable", "Unavailable"),
                ],
                db_index=True,
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="reminder_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("informational", "Informational"),
                    ("acknowledgement", "Acknowledgement"),
                    ("action", "Action"),
                ],
                default="informational",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="unavailable_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "outcome_state", "-created_at"],
                name="notif_outcome_cursor_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["active_follow_up", "due_at"], name="notif_followup_due_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("active_follow_up", True), models.Q(("dedupe_key", ""), _negated=True)
                ),
                fields=("recipient", "dedupe_key"),
                name="unique_active_notification_followup",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("active_follow_up", False),
                        ("outcome_state", "not_required"),
                        ("requirement_type", "informational"),
                    ),
                    models.Q(
                        models.Q(("requirement_type", "informational"), _negated=True),
                        models.Q(("outcome_state", "not_required"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="notification_requirement_outcome_valid",
            ),
        ),
        migrations.AddField(
            model_name="notificationdeliveryattempt",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_attempts",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferenceprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preference_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationcategorypreference",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_preferences",
                to="notifications.notificationpreferenceprofile",
            ),
        ),
        migrations.AddField(
            model_name="projectnotificationpolicy",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_policy",
                to="projects.researchproject",
            ),
        ),
        migrations.AddField(
            model_name="projectnotificationpolicy",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_project_notification_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliveryattempt",
            index=models.Index(fields=["state", "eligible_at"], name="notif_attempt_due_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationdeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("notification", "channel", "attempt_number"),
                name="unique_notification_channel_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationcategorypreference",
            constraint=models.UniqueConstraint(
                fields=("profile", "category"), name="unique_notification_category_preference"
            ),
        ),
    ]
