# Generated by Django 5.2.15 on 2026-07-20 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notifications", "0006_notification_delivery_policy_and_more"),
        ("projects", "0002_project_materials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("personal", "Personal"), ("group", "Group")],
                        default="personal",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("meeting", "Meeting"),
                            ("seminar", "Seminar"),
                            ("milestone", "Milestone"),
                            ("defense", "Defense"),
                            ("deadline", "Deadline"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=4000)),
                ("all_day", models.BooleanField(default=False)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "recurrence_frequency",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("recurrence_interval", models.PositiveSmallIntegerField(default=1)),
                ("recurrence_weekdays", models.JSONField(blank=True, default=list)),
                ("recurrence_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_schedule_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_schedule_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("project", "Project"), ("account", "Account")], max_length=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_schedule_audiences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.researchproject",
                    ),
                ),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiences",
                        to="schedules.scheduleitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleNotificationDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurrence_key", models.CharField(max_length=40)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("changed", "Changed"),
                            ("cancelled", "Cancelled"),
                            ("removed", "Removed"),
                            ("reminder", "Reminder"),
                        ],
                        max_length=16,
                    ),
                ),
                ("offset_minutes", models.IntegerField(blank=True, null=True)),
                ("offset_key", models.IntegerField(default=-1, editable=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In app"), ("email", "Email")], max_length=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("claimed", "Claimed"),
                            ("created", "Created"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="claimed",
                        max_length=12,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.notification",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_dispatches",
                        to="schedules.scheduleitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleOccurrenceException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_starts_at", models.DateTimeField(blank=True, null=True)),
                ("original_starts_on", models.DateField(blank=True, null=True)),
                ("override_starts_at", models.DateTimeField(blank=True, null=True)),
                ("override_ends_at", models.DateTimeField(blank=True, null=True)),
                ("override_starts_on", models.DateField(blank=True, null=True)),
                ("override_ends_on", models.DateField(blank=True, null=True)),
                ("override_title", models.CharField(blank=True, max_length=255, null=True)),
                ("override_description", models.TextField(blank=True, max_length=4000, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rescheduled", "Rescheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="rescheduled",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="schedules.scheduleitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleRecipientGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("source_types", models.JSONField(default=list)),
                ("source_project_ids", models.JSONField(blank=True, default=list)),
                ("resolved_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_grants",
                        to="schedules.scheduleitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("offset_minutes", models.PositiveIntegerField()),
                ("mandatory", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="schedules.scheduleitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("content_changed", "Content changed"),
                            ("time_changed", "Time changed"),
                            ("audience_changed", "Audience changed"),
                            ("occurrence_changed", "Occurrence changed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=24,
                    ),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("audience_summary", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="schedules.scheduleitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-revision_number"],
            },
        ),
        migrations.AddIndex(
            model_name="scheduleitem",
            index=models.Index(
                fields=["owner", "scope", "status", "starts_at"], name="sched_owner_timed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleitem",
            index=models.Index(
                fields=["owner", "scope", "status", "starts_on"], name="sched_owner_day_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleitem",
            index=models.Index(
                fields=["scope", "status", "published_at"], name="sched_group_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleitem",
            index=models.Index(
                fields=["recurrence_frequency", "recurrence_until"], name="sched_recur_until_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleitem",
            index=models.Index(fields=["updated_at", "id"], name="sched_event_cursor_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduleaudience",
            index=models.Index(
                fields=["schedule_item", "scope_type"], name="sched_audience_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleaudience",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("schedule_item", "project"),
                name="unique_schedule_project_audience",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleaudience",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", False)),
                fields=("schedule_item", "account"),
                name="unique_schedule_account_audience",
            ),
        ),
        migrations.AddIndex(
            model_name="schedulenotificationdispatch",
            index=models.Index(fields=["status", "created_at"], name="sched_dispatch_retry_idx"),
        ),
        migrations.AddConstraint(
            model_name="schedulenotificationdispatch",
            constraint=models.UniqueConstraint(
                fields=(
                    "schedule_item",
                    "recipient",
                    "occurrence_key",
                    "event_type",
                    "offset_key",
                    "channel",
                ),
                name="unique_schedule_dispatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrenceexception",
            constraint=models.UniqueConstraint(
                condition=models.Q(("original_starts_at__isnull", False)),
                fields=("schedule_item", "original_starts_at"),
                name="unique_schedule_timed_exception",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrenceexception",
            constraint=models.UniqueConstraint(
                condition=models.Q(("original_starts_on__isnull", False)),
                fields=("schedule_item", "original_starts_on"),
                name="unique_schedule_day_exception",
            ),
        ),
        migrations.AddIndex(
            model_name="schedulerecipientgrant",
            index=models.Index(
                fields=["recipient", "schedule_item", "valid_from", "valid_until"],
                name="sched_grant_visible_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schedulerecipientgrant",
            index=models.Index(
                fields=["schedule_item", "valid_until"], name="sched_grant_open_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulerecipientgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("valid_until__isnull", True)),
                fields=("schedule_item", "recipient"),
                name="unique_open_schedule_grant",
            ),
        ),
        migrations.AddIndex(
            model_name="schedulereminder",
            index=models.Index(
                fields=["offset_minutes", "schedule_item"], name="sched_reminder_scan_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulereminder",
            constraint=models.UniqueConstraint(
                fields=("schedule_item", "offset_minutes"), name="unique_schedule_reminder"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulerevision",
            constraint=models.UniqueConstraint(
                fields=("schedule_item", "revision_number"), name="unique_schedule_revision"
            ),
        ),
    ]
