# Generated by Django 5.2.15 on 2026-07-24 05:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_access_governance_roles"),
        ("submissions", "0006_projectreportschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionReviewAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("removed", "Removed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_review_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "draft_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to="submissions.draftversion",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="removed_review_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_assignments",
                        to="projects.projectmembership",
                    ),
                ),
                (
                    "weekly_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to="submissions.weeklyprogressreport",
                    ),
                ),
                (
                    "writing_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to="submissions.writingversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["reviewer_membership", "status", "-assigned_at"],
                        name="sub_review_member_idx",
                    ),
                    models.Index(fields=["weekly_report", "status"], name="sub_review_weekly_idx"),
                    models.Index(
                        fields=["writing_version", "status"], name="sub_review_writing_idx"
                    ),
                    models.Index(fields=["draft_version", "status"], name="sub_review_draft_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("weekly_report__isnull", False),
                                ("writing_version__isnull", True),
                                ("draft_version__isnull", True),
                            ),
                            models.Q(
                                ("weekly_report__isnull", True),
                                ("writing_version__isnull", False),
                                ("draft_version__isnull", True),
                            ),
                            models.Q(
                                ("weekly_report__isnull", True),
                                ("writing_version__isnull", True),
                                ("draft_version__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="review_assignment_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active"), ("weekly_report__isnull", False)),
                        fields=("reviewer_membership", "weekly_report"),
                        name="unique_active_weekly_review_assignment",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status", "active"), ("writing_version__isnull", False)
                        ),
                        fields=("reviewer_membership", "writing_version"),
                        name="unique_active_writing_review_assignment",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("draft_version__isnull", False), ("status", "active")),
                        fields=("reviewer_membership", "draft_version"),
                        name="unique_active_draft_review_assignment",
                    ),
                ],
            },
        ),
    ]
