# Generated by Django 5.2.15 for deliverable review assignments.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_research_execution"),
        ("submissions", "0007_review_assignments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="submissionreviewassignment",
            name="review_assignment_exactly_one_target",
        ),
        migrations.AddField(
            model_name="submissionreviewassignment",
            name="deliverable_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_assignments",
                to="projects.deliverablerevision",
            ),
        ),
        migrations.AddIndex(
            model_name="submissionreviewassignment",
            index=models.Index(
                fields=["deliverable_revision", "status"], name="sub_review_deliverable_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionreviewassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("weekly_report__isnull", False),
                        ("writing_version__isnull", True),
                        ("draft_version__isnull", True),
                        ("deliverable_revision__isnull", True),
                    ),
                    models.Q(
                        ("weekly_report__isnull", True),
                        ("writing_version__isnull", False),
                        ("draft_version__isnull", True),
                        ("deliverable_revision__isnull", True),
                    ),
                    models.Q(
                        ("weekly_report__isnull", True),
                        ("writing_version__isnull", True),
                        ("draft_version__isnull", False),
                        ("deliverable_revision__isnull", True),
                    ),
                    models.Q(
                        ("weekly_report__isnull", True),
                        ("writing_version__isnull", True),
                        ("draft_version__isnull", True),
                        ("deliverable_revision__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="review_assignment_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionreviewassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deliverable_revision__isnull", False), ("status", "active")),
                fields=("reviewer_membership", "deliverable_revision"),
                name="unique_active_deliverable_review_assignment",
            ),
        ),
    ]
