# Generated by Django 5.2.15 for feature 017 structured reporting.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_research_execution"),
        ("submissions", "0008_deliverable_review_assignments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("label_en", models.CharField(max_length=255)),
                ("label_zh", models.CharField(max_length=255)),
                ("help_text_en", models.TextField(blank=True, max_length=1000)),
                ("help_text_zh", models.TextField(blank=True, max_length=1000)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("long_text", "Long text"),
                            ("number", "Number"),
                            ("percentage", "Percentage"),
                            ("single_choice", "Single choice"),
                            ("multiple_choice", "Multiple choice"),
                            ("execution_progress", "Execution progress"),
                            ("risk_blocker", "Risk or blocker"),
                        ],
                        max_length=32,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField()),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("options", models.JSONField(blank=True, default=list)),
                (
                    "min_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "max_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
                ),
                ("analytics_enabled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="weeklyprogressreport",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weeklyprogressreport",
            name="response_schema_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="weeklyprogressreport",
            name="submitted_late",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ReportingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("deadline_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("generation_key", models.CharField(max_length=160, unique=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_periods",
                        to="projects.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_on"],
            },
        ),
        migrations.AddField(
            model_name="weeklyprogressreport",
            name="reporting_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="submissions.reportingperiod",
            ),
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_template",
                        to="projects.researchproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.JSONField()),
                (
                    "numeric_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("milestone", "Milestone"),
                            ("deliverable", "Deliverable"),
                            ("risk", "Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_responses",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="submissions.weeklyprogressreport",
                    ),
                ),
                (
                    "template_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="submissions.reporttemplatefield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_report_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_template_versions",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_report_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="submissions.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="reporttemplatefield",
            name="template_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="submissions.reporttemplateversion",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="submissions.reporttemplateversion",
            ),
        ),
        migrations.AddField(
            model_name="reportingperiod",
            name="template_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reporting_periods",
                to="submissions.reporttemplateversion",
            ),
        ),
        migrations.AddField(
            model_name="weeklyprogressreport",
            name="template_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="submissions.reporttemplateversion",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyprogressreport",
            index=models.Index(
                fields=["reporting_period", "student", "-revision_number"],
                name="sub_report_period_student_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyprogressreport",
            index=models.Index(
                fields=["project", "submitted_late", "review_status", "submitted_at"],
                name="sub_report_lateness_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyprogressreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("project", "student", "idempotency_key"),
                name="unique_structured_report_retry",
            ),
        ),
        migrations.AddIndex(
            model_name="reportresponse",
            index=models.Index(
                fields=["project", "template_field", "numeric_value"],
                name="sub_response_metric_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportresponse",
            index=models.Index(fields=["report", "template_field"], name="sub_response_report_idx"),
        ),
        migrations.AddIndex(
            model_name="reportresponse",
            index=models.Index(fields=["source_type", "source_id"], name="sub_response_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="reportresponse",
            constraint=models.UniqueConstraint(
                fields=("report", "template_field"), name="unique_report_field_response"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplateversion",
            index=models.Index(
                fields=["project", "status", "version_number"],
                name="sub_template_project_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplateversion",
            index=models.Index(
                fields=["template", "status"], name="sub_template_version_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version_number"), name="unique_report_template_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplateversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("template",),
                name="unique_draft_report_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplateversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("template",),
                name="unique_published_report_template",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplatefield",
            index=models.Index(
                fields=["template_version", "order"], name="sub_template_field_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplatefield",
            index=models.Index(
                fields=["template_version", "analytics_enabled", "field_type"],
                name="sub_template_field_metric_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplatefield",
            constraint=models.UniqueConstraint(
                fields=("template_version", "key"), name="unique_report_template_field_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplatefield",
            constraint=models.UniqueConstraint(
                fields=("template_version", "order"), name="unique_report_template_field_order"
            ),
        ),
        migrations.AddIndex(
            model_name="reportingperiod",
            index=models.Index(
                fields=["project", "starts_on", "state"], name="sub_period_project_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportingperiod",
            index=models.Index(fields=["state", "deadline_at"], name="sub_period_deadline_idx"),
        ),
        migrations.AddIndex(
            model_name="reportingperiod",
            index=models.Index(
                fields=["template_version", "starts_on"], name="sub_period_template_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportingperiod",
            constraint=models.UniqueConstraint(
                fields=("project", "starts_on"), name="unique_project_reporting_period"
            ),
        ),
    ]
