# Generated by Django 5.2.15 on 2026-07-29 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_decisions_and_risks"),
        ("resources", "0005_booking_origin_completion_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceitem",
            name="calibration_interval_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="kind",
            field=models.CharField(
                choices=[("equipment", "Equipment"), ("consumable", "Consumable")],
                default="equipment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="next_calibration_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="reorder_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="stock_on_hand",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="stock_unit",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="ConsumableStockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("issue", "Issue"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_delta", models.IntegerField()),
                ("balance_after", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("note", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumable_transactions",
                        to="projects.researchproject",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_consumable_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="resources.resourceitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["resource_item", "-recorded_at"],
                        name="consumable_resource_time_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_delta", 0), _negated=True),
                        name="consumable_quantity_delta_nonzero",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourceMaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive maintenance"),
                            ("calibration", "Calibration"),
                            ("repair", "Repair"),
                            ("fault", "Fault"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=255)),
                ("scheduled_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("takes_offline", models.BooleanField(default=True)),
                ("cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_resource_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_resource_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="resources.resourceitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["resource_item", "status", "scheduled_at"],
                        name="resource_maint_status_idx",
                    )
                ],
            },
        ),
    ]
